version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT=1
    container_name: backend 
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "5000:5000"  
    networks:
      - app-network

  nginx: 
    image: nginx:alpine
    container_name: nginx
#    depends_on:
#      - backend
#      - frontend
    ports:
      - "8080:8080" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
