version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"  # Nginx가 8080 포트로 내부 백엔드에 접근
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local