spring:
  jpa:
    hibernate:
      ddl-auto: create
  redis:
    host: redis
    port: 6379
    password: ${REDIS_PASSWORD}
    timeout: 5000ms

logging:
  level:
    org.springframework.security: DEBUG
