server:
  forward-headers-strategy: native

spring:
  application:
    name: finalbackend

  datasource:
    writer:
      hikari:
        jdbc-url: jdbc:mariadb://motive.cdw8kw8go27z.ap-northeast-2.rds.amazonaws.com:3306/motive
        username: admin
        password: motivepassword
        driver-class-name: org.mariadb.jdbc.Driver

    reader:
      hikari:
        jdbc-url: jdbc:mariadb://readonlymotive.cdw8kw8go27z.ap-northeast-2.rds.amazonaws.com:3306/motive
        username: admin
        password: motivepassword
        driver-class-name: org.mariadb.jdbc.Driver


  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host:
      port:
        username: ${EMAIL_ID}
        password: ${EMAIL_PWD}
        properties:
          mail.smtp.auth: true
          mail.smtp.ssl.enable: true
          mail.smtp.ssl.trust: ${EMAIL_HOST}
          mail.smtp.ssl.protocols: TLSv1.2
          mail.debug: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  header: ${JWT_HEADER}

encryption:
  algorithm: ${ALGORITHM}
  transformation: ${TRANSFORMATION}
  secret-key: ${SECRET_DEFAULT_KEY}


logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
      apache.ibatis: DEBUG
      mybatis: DEBUG
    jdbc.sqltiming: DEBUG
    jdbc.resultsettable: TRACE

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESSKEY}
      secret-key: ${S3_SECRETKEY}
    s3:
      bucket: ${S3_BUCKETNAME}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

claude:
  api:
    key: ${CLAUDE_API_KEY}
    url: https://api.claude.ai/v1/summary

naver:
  client-id: CdxW72qcvZLVTHrViB20
  client-secret: ZjP2cbXlfU