server:
  forward-headers-strategy: native

spring:
  application:
    name: ${SPRING_APP_NAME}

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATABASE_HOST}:${MARIA_DATABASE_PORT}/${MARIA_DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  secret-default-value: ${JWT_SECRET_DEFAULT_VALUE}
  header: ${JWT_HEADER}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

#server:
#  servlet:
#    session:
#      timeout: ${SESSION_TIMEOUT:20m}