server:
  forward-headers-strategy: native


spring:
  application:
    name: finalbackend

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://${DATABASE_URL}:${MARIA_DATABASE_PORT}/${MARIA_DATABASE_NAME}
    url: jdbc:mariadb://motive.cdw8kw8go27z.ap-northeast-2.rds.amazonaws.com:3306/motive
    username: admin
    password: motivepassword
  #    username: ${DB_USERNAME}
  #    password: ${DB_PASSWORD}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret-key: s4G7tL9qH8vI2eP0j5W1uF3bM6nK8rXc
  header: Authorization

encryption:
  algorithm: AES
  transformation: AES/ECB/PKCS5Padding
  secret-key: haWh*9teA@2sT!nLaO$i0lEcj3cU282d


logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESSKEY}
      secret-key: ${S3_SECRETKEY}
    s3:
      bucket: ${S3_BUCKETNAME}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
