server:
  forward-headers-strategy: native


spring:
  application:
    name: finalbackend

  datasource:
    writer:
      hikari:
        jdbc-url: jdbc:mariadb://motive.cdw8kw8go27z.ap-northeast-2.rds.amazonaws.com:3306/motive
        username: admin
        password: motivepassword
        driver-class-name: org.mariadb.jdbc.Driver

    reader:
      hikari:
        jdbc-url: jdbc:mariadb://readonlymotive.cdw8kw8go27z.ap-northeast-2.rds.amazonaws.com:3306/motive
        username: admin
        password: motivepassword
        driver-class-name: org.mariadb.jdbc.Driver


  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host:
      port:
        username: stanl2e2@naver.com
        password: "Stanl222"
        properties:
          mail.smtp.auth: true
          mail.smtp.ssl.enable: true
          mail.smtp.ssl.trust: smtp.naver.com
          mail.smtp.ssl.protocols: TLSv1.2
          mail.debug: true

  jwt:
    secret-key: s4G7tL9qH8vI2eP0j5W1uF3bM6nK8rXc
    header: Authorization


  encryption:
    algorithm: AES
    transformation: AES/ECB/PKCS5Padding
    secret-key: haWh*9teA@2sT!nLaO$i0lEcj3cU282d



  logging:
    pattern:
      console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
    level:
      org:
        springframework:
          security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

    cloud:
      aws:
        credentials:
          access-key: AKIAQE3ROMWSWEBT7F7O
          secret-key: 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
        s3:
          bucket: motivebk
        region:
          static: ap-northeast-2
        stack:
          auto: false

    mybatis:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#    claude:
#      api:
#        key: ${CLAUDE_API_KEY}
#        url: https://api.claude.ai/v1/summary

    naver:
      client-id: CdxW72qcvZLVTHrViB20
      client-secret: ZjP2cbXlfU


