SET foreign_key_checks = 0;

-- 테이블 삭제 순서
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS CENTER;
DROP TABLE IF EXISTS SCHEDULE;

-- 테이블 생성
CREATE TABLE member (
    MEM_ID VARCHAR(255) NOT NULL PRIMARY KEY
);

CREATE TABLE center (
    CENT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
    CENT_NAME VARCHAR(255) NOT NULL,
    CENT_ADR VARCHAR(255) NOT NULL,
    CENT_PHO VARCHAR(255) NOT NULL,
    CENT_MEM_CNT INTEGER NOT NULL,
    CENT_OPR_AT VARCHAR(255) NOT NULL,
    CREATED_AT CHAR(19) NOT NULL,
    UPDATED_AT CHAR(19) NOT NULL DEFAULT CREATED_AT,
    DELETED_AT CHAR(19) NULL,
    ACTIVE BOOLEAN NOT NULL
);

CREATE TABLE schedule (
    SCH_ID VARCHAR(255) NOT NULL PRIMARY KEY,
    SCH_NAME VARCHAR(255) NOT NULL,
    SCH_CONT VARCHAR(255) NOT NULL,
    SCH_RES CHAR(19) NOT NULL,
    CREATED_AT CHAR(19) NOT NULL,
    UPDATED_AT CHAR(19) NOT NULL DEFAULT CREATED_AT,
    DELETED_AT CHAR(19) NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    MEM_ID VARCHAR(255) NOT NULL
);

-- 제약 조건 추가
ALTER TABLE schedule ADD CONSTRAINT FK_MEM_ID FOREIGN KEY (MEM_ID) REFERENCES member(MEM_ID);

-- 더미 데이터 삽입

