name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
      - feat/backend-operation

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      APPLICATION_NAME: "motive-backend"
      ENVIRONMENT_NAME: "Motive-backend-env"

    steps:
      # 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # backend 디렉토리로 이동
      - name: Change to backend directory
        run: cd backend

      # Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker 이미지 빌드
      - name: Build Docker images
        working-directory: backend
        run: docker-compose build

      # Elastic Beanstalk CLI 설치
      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install awsebcli --upgrade

      # AWS 자격 증명 구성
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Elastic Beanstalk 배포
      - name: Deploy to Elastic Beanstalk
        working-directory: backend
        run: |
          eb init ${{ env.APPLICATION_NAME }} --platform "Docker" --region ${{ env.AWS_REGION }}
          eb use ${{ env.ENVIRONMENT_NAME }}
          eb deploy --staged
