name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
      - feat/backend-operation

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      APPLICATION_NAME: "motive-backend"
      ENVIRONMENT_NAME: "Motive-backend-env"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker-compose build

      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install awsebcli --upgrade

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p "Docker" ${{ env.APPLICATION_NAME }} --region ${{ env.AWS_REGION }}
          eb use ${{ env.ENVIRONMENT_NAME }}
          eb deploy --staged
