name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
      - feat/backend-operation

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      APPLICATION_NAME: "motive-backend"
      ENVIRONMENT_NAME: "Motive-backend-env"

    steps:
      # 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker 및 Docker Compose 버전 확인
      - name: Check Docker and Docker Compose
        run: |
          docker --version
          docker compose version

      # JDK 17 설정 (Gradle 빌드용)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      # gradlew 실행 권한 설정
      - name: Set executable permission for gradlew
        run: chmod +x gradlew

      # Gradle 빌드 (JAR 파일 생성)
      - name: Build and package the application
        run: ./gradlew clean build -x test

      # Elastic Beanstalk CLI 설치
      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install awsebcli --upgrade

      # AWS 자격 증명 구성
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Elastic Beanstalk 배포
      - name: Deploy to Elastic Beanstalk
        run: |
          eb init ${{ env.APPLICATION_NAME }} --platform "Docker" --region ${{ env.AWS_REGION }} --verbose
          eb use ${{ env.ENVIRONMENT_NAME }}
          eb deploy --verbose
